spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: C:\Users\secureletter\Desktop\git-local-repo
          default-label: master
server:
  port: 8888
